
const f = () =>{

try
{
    let a = 0
    // console.log(program)
    console.log("Program run successfully")
    return
}
catch(err)
{
    console.log("This is an error")
    console.log(p)
}
finally
{
    console.log("I am good")
}
}

f()

console.log("End")